site_name: Notes
repo_url: https://github.com/yuuushan/notes
repo_name: yuuushan/notes

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - add-number:
      order: 2

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_truly_sane_lists

nav:
  - index.md
  - Go:
      - go/slice.md
      - go/map.md
      - go/channel.md
      - Gin:
          - go/gin/getting_started_with_gin.md
          - go/gin/live_reload_for_gin.md
          - go/gin/gin_request_parameter_processing.md
